### ISSUE TITLE
[Feature Request] Increase in scroll speed if draggable hold down for long enough

### ISSUE THREAD

**Issue by brightseagit** [huhuang03/reorderable_grid_view#10]
Hello,
It would be great if you can increase the scrolling speed if we keep holding the draggable when scrolling for a longer time as it is hard to scroll with the draggable at the current speed. Slow at the start of the scroll and then become fast after few seconds.
Thank you.

**Comment by huhuang03** [comment]
Maybe you can try `1.1.0-alpha.2`, which add the option `scrollSpeedController`, param `timeInMilliSecond` is the time passed. Return how many pixels scroll in 14ms.

**Comment by brightseagit** [comment]
Very great solution. 
Thank you 👍 for considering this feature.
