### ISSUE TITLE
[Issue] Plugin version 1.1.0-alpha.3 on pub.dev doesn't include the new changes.

### ISSUE THREAD

**Issue by brightseagit** [huhuang03/reorderable_grid_view#15]
| Pub.dev 1.1.0-alpha.3 | Current Repo code |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/72334435/127216582-a0a9e1ce-9625-4ccc-aea5-b178c1144953.png)| ![image](https://user-images.githubusercontent.com/72334435/127216676-ffcde945-9b59-4156-ad26-7cbb98d68905.png) |

**Comment by huhuang03** [comment]
merge mistake, I will publish alpha.4
