### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by TusharRoy23** [huhuang03/reorderable_grid_view#16]
SDK version - `sdk: ">=2.11.0 <3.0.0"`. 
Maybe it occurs because of the version.
Like - `bool isMoveLeft = _dropIndex! > _dragIndex!;` for this one =>  `!`
 How am I going to solve this one?

**Comment by huhuang03** [comment]
I can't guess what's happen. Can you provider a log, thanks.

**Comment by TusharRoy23** [comment]
This is it which I get from log 
`Null check operator used on a null value`
And I manage to run my application after removing the NULL check operator.

**Comment by huhuang03** [comment]
I think it's some issue of the nullsafety. Can you try upgrade the sdk version to 2.12.0..

**Comment by huhuang03** [comment]
I will close this issue. You can reopen if need.

**Comment by sushantdhumal** [comment]
> Yes, it's some issue of the nullsafety. Can you try upgrade the sdk version to 2.12.0..

For some reason, I can't update sdk version to 2.12.0. for now. Is there any other way to solve this issue?

**Comment by liangxianshen** [comment]
This error is very rare. Flutter SDK 3.13.4.

Log:  Null check operator used on a null value

State.context | (package:flutter/src/widgets/framework.dart:957)
DragInfo._scrollIfNeed | (package:reorderable_grid_view/src/drag_info.dart:190)
DragInfo.update | (package:reorderable_grid_view/src/drag_info.dart:169)
MultiDragPointerState._move | (package:flutter/src/gestures/multidrag.dart:92)
MultiDragGestureRecognizer._handleEvent | (package:flutter/src/gestures/multidrag.dart:254)
PointerRouter._dispatch | (package:flutter/src/gestures/pointer_router.dart:98)
PointerRouter._dispatchEventToRoutes.<anonymous closure> | (package:flutter/src/gestures/pointer_router.dart:143)
_LinkedHashMapMixin.forEach | (dart:collection-patch/compact_hash.dart:625)
PointerRouter._dispatchEventToRoutes | (package:flutter/src/gestures/pointer_router.dart:141)
PointerRouter.route | (package:flutter/src/gestures/pointer_router.dart:127)
GestureBinding.handleEvent | (package:flutter/src/gestures/binding.dart:488)
GestureBinding.dispatchEvent | (package:flutter/src/gestures/binding.dart:468)
RendererBinding.dispatchEvent | (package:flutter/src/rendering/binding.dart:333)
GestureBinding._handlePointerEventImmediately | (package:flutter/src/gestures/binding.dart:413)
 GestureBinding.handlePointerEvent | (package:flutter/src/gestures/binding.dart:376)
 GestureBinding._flushPointerEventQueue | (package:flutter/src/gestures/binding.dart:323)
GestureBinding._handlePointerDataPacket | (package:flutter/src/gestures/binding.dart:292)
_rootRunUnary | (dart:async/zone.dart:1415)
_CustomZone.runUnary | (dart:async/zone.dart:1308)
_CustomZone.runUnaryGuarded | (dart:async/zone.dart:1217)
_invoke1 | (dart:ui/hooks.dart:188)
PlatformDispatcher._dispatchPointerDataPacket | (dart:ui/platform_dispatcher.dart:424)
_dispatchPointerDataPacket | (dart:ui/hooks.dart:119)

**Comment by huhuang03** [comment]
Thank you for report. I can't locate the reason. I add some maybe fix, and you can try version `2.2.9-alpha.2` if need.
