### ISSUE TITLE
[Feature Request] Add itemBuilder and sliver support.

### ISSUE THREAD

**Issue by idish** [huhuang03/reorderable_grid_view#18]
itemBuilder is very important feature, so we can build the items on demand, and not supply all the children at once.
sliver support is important as well, as if we can create custom scrolling experience. (Check `SliverReorderableList`).

Thanks for this amazing library! A very needed  flutter capability indeed.

**Comment by huhuang03** [comment]
Sorry for the late.

Please try `2.0.0-alpha.1`. See `example/lib/demo_grid_builder.drat` for detail.

You need set 
```
          crossAxisSpacing: 10,
          mainAxisSpacing: 10,
          crossAxisCount: 3,
          childAspectRatio: 0.6,
```
twrice for now, because this lib use those to calc the position of child.

**Comment by huhuang03** [comment]
Sorry for so late. My work is not about flutter recently. You can try `2.1.0-alpha-1` if still need, bring the `ReorderableSliverGridView.count`.

**Comment by huhuang03** [comment]
I will close this for now, because `2.2.0` impl the `ReorderableSliverGridView`. Reopen it if still have some issue.
