### ISSUE TITLE
Add scrolling through the dragable

### ISSUE THREAD

**Issue by brightseagit** [huhuang03/reorderable_grid_view#2]
Great plugin but please also add a property for scrolling by dragging the draggable down in the gridview.

Current behavior: 
Cannot scroll using the draggable:
![draggable](https://user-images.githubusercontent.com/72334435/122886371-88794400-d35d-11eb-9241-c7003e31acfc.gif)

Expected behavior:
Example of google keep notes:
![draggable scroll](https://user-images.githubusercontent.com/72334435/122886213-6384d100-d35d-11eb-9d96-7af37e54aa67.gif)

Thank you.

**Comment by brightseagit** [comment]
Hello,
Sorry for asking but can you please let me know if you are going to implement this feature in the plugin.
This feature is important for my project so I just wanted to know.
And it's fine if it takes time to build.

Thanks.

**Comment by huhuang03** [comment]
I'm sorry it seems too hard for me. Maybe you can look for another project or try implement it by reading the official `reorderable_list_view`.

**Comment by brightseagit** [comment]
It's fine. Thanks for letting me know about that. I will look if I can find a alternative or a way to implement that feature in this plugin.

**Comment by brightseagit** [comment]
Hey,
I tried a lot to find an alternative but I failed to find one. But I previously tried this package https://github.com/DevOrbiter/drag_and_drop_gridview which does provide scrolling but I didn't use it because it has some other issues also. 
So, I tried implementing scrolling in your plugin by using that plugin as a reference but I failed. So I was thinking if you can have a look at this package for an idea on implementing scrolling in your plugin then it would be a great help to me.

I did found that the drag_and_drop_gridview plugin is using ScrollController to animate scroll with grid height on OnWillAccept using moveUp, moveDown functions in ```gridOrbiter.dart``` in the plugin.

Thank you.

**Comment by brightseagit** [comment]
Hello,
I'm sorry to bother you again 😅 but it would be great for me to know if you have any updates regarding it.

Thank you.

**Comment by huhuang03** [comment]
You can try version `1.1.0-alpha` if you still need it, I'm sorry I don't have much time to do this.

**Comment by brightseagit** [comment]
@huhuang03 It's okay I can understand that time is tight sometimes. But thank you very much for adding the scrolling functionality as I was still in need of a reorderable gridview plugin but now your plugin fulfills my project requirement I'm going to use it. Thanks again.
