### ISSUE TITLE
Is there any option for placeholder when we drag item?

### ISSUE THREAD

**Issue by beamAkshay** [huhuang03/reorderable_grid_view#27]

**Comment by huhuang03** [comment]
For now, it's not, but maybe can add an option for an placehodler builder.

**Comment by beamAkshay** [comment]
Please add it.

**Comment by huhuang03** [comment]
Please try version ~2.2.3-alpha.1~. Added the ~placeholderBuilder~ option.

**Comment by beamAkshay** [comment]
Thanks
