### ISSUE TITLE
Stopping multiple draggables from dragging at the same time

### ISSUE THREAD

**Issue by brightseagit** [huhuang03/reorderable_grid_view#3]
Please also provide a way to stop multiple draggables from dragging at the same time. For example, if I long-press a draggable to drag it, I can still long-press and drag the other draggables.

Current behavior:
![multiple drags](https://user-images.githubusercontent.com/72334435/122885164-734fe580-d35c-11eb-8070-ba72718e8add.gif)

Expected behavior:
Example of google keep notes:
![no multiple drags](https://user-images.githubusercontent.com/72334435/122885489-c2961600-d35c-11eb-92dd-33aa1be8d0e3.gif)

**Comment by huhuang03** [comment]
You can now use new version `1.0.0` which add `antiMultiDrag`, set it to `true` will do that.

**Comment by brightseagit** [comment]
Thanks for looking into this issue and adding the property in plugin.
