### ISSUE TITLE
In flutter 3.0.1 it is giving error 

### ISSUE THREAD

**Issue by clebemachado** [huhuang03/reorderable_grid_view#30]
this is the error:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      new ReorderableGridView.builder.<anonymous closure> (package:reorderable_grid_view/reorderable_grid_view.dart:108:64)

```

Note: in gridview.build everything is working fine

**Comment by huhuang03** [comment]
Hello, I looked the log. It seems not the newest code.

Which version of this lib do you use.

And please try the newest version `2.2.3-alpha.1` to see if the error still exists.

**Comment by doubletcjs** [comment]
@clebemachado 
set key for earch item, dragWidget or footer

**Comment by Bikuta-victor1** [comment]
i am getting this error using ReorderableGridView.builder on version 2.2.3-alpha.1

**Comment by huhuang03** [comment]
Can you try latest `2.2.6-alpha.11` version, and post the error log if still has error. I want see which line is error in the error log.

**Comment by arioul89** [comment]
Same of me on Flutter 3.7.1, event with 2.2.6-alpha.11, here is the Stacktrace :

#84     RenderBox.layout
package:flutter/…/rendering/box.dart:2430
#85     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:120
#86     RenderObject.layout
package:flutter/…/rendering/object.dart:2189
#87     RenderBox.layout
package:flutter/…/rendering/box.dart:2430
#88     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:120
#89     RenderOffstage.performLayout
package:flutter/…/rendering/proxy_box.dart:3815
#90     RenderObject.layout
package:flutter/…/rendering/object.dart:2189
#91     RenderBox.layout
package:flutter/…/rendering/box.dart:2430
#92     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:120
#93     RenderObject.layout
package:flutter/…/rendering/object.dart:2189
#94     RenderBox.layout
package:flutter/…/rendering/box.dart:2430
#95     _RenderTheatre.performLayout
package:flutter/…/widgets/overlay.dart:856
#96     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:2027
#97     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:1020
#98     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:516
#99     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:865
#100    RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:381
#101    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1289
#102    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1218
#103    SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1076
#104    _invoke (dart:ui/hooks.dart:145:13)
#105    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#106    _drawFrame (dart:ui/hooks.dart:112:31)

**Comment by huhuang03** [comment]
Thank you for your reminder, I will update that.
