### ISSUE TITLE
No header?

### ISSUE THREAD

**Issue by ZFRong** [huhuang03/reorderable_grid_view#32]
Can I add a header at the top of the List like the footer?

**Comment by huhuang03** [comment]
。。。For now, there is not, but I think I can dad that option.

**Comment by huhuang03** [comment]
Please try version `2.2.3-alpha.3`, add an option `header` in `Reorderable.count`. But please notice, `header` and `footer` ony support in `Reorderable.count`. Ff you need support in other type constractor, please leve an comment.
