### ISSUE TITLE
Dragging rounded widget adds rectangular white container

### ISSUE THREAD

**Issue by 0x-cell** [huhuang03/reorderable_grid_view#44]
Hey, I have a grid of items which has rounded corners. When dragging the widget the widget is wrapped in a rectangular white container. Is there a way to override the wrapped widget decoration/style?

Example (right picture is dragged)
![obraz](https://user-images.githubusercontent.com/69264477/192101205-bae89cf0-696a-49d4-acf1-7e817883fc9f.png)

**Comment by 0x-cell** [comment]
Figured out that we can use `dragWidgetBuilder` to do that. Thanks.

**Comment by huhuang03** [comment]
Thanks. I will update Readme to point out this.
