### ISSUE TITLE
Dynamic crossAxisCount

### ISSUE THREAD

**Issue by yegor-pelykh** [huhuang03/reorderable_grid_view#48]
Is it possible to make a version of the constructor for ReorderableGridView where it would not be necessary to set the crossAxisCount, but this count was dynamic and dependent on the amount of free space allocated to this ReorderableGridView?

I think it should be possible.

**Comment by huhuang03** [comment]
It's not in plan. Because:
1. seem the official `GridView` not support this.
2. If craclAxisCont calc by child width, but child width is calc by `crossAxisCount`, so it's a sycle calc.

**Comment by yegor-pelykh** [comment]
Yes, I agree with you.
I was able to calculate the `crossAxisCount` dynamically outside of your widget based on the maximum available width.
I think the issue is closed then.
Thanks for the great widget! 👍
