### ISSUE TITLE
The offset is not right when draging grid_view 

### ISSUE THREAD

**Issue by mnba3223** [huhuang03/reorderable_grid_view#49]
HI. I use your amazing package normally, until I add nested router in this.
 
And this is position incorrect when I draging the gridveiw item in our app.

![1666924453595](https://user-images.githubusercontent.com/15074534/198471916-9700f046-5c7e-4547-968a-6c7998a06020.gif)

But when I take off the nested router, it's work fine.

**Comment by huhuang03** [comment]
Hello, maybe you can try 
```
ReorderableSliverGridView.count
```

instead of 
```
ReorderableGridView
```

**Comment by mnba3223** [comment]
> Hello, maybe you can try
> 
> ```
> ReorderableSliverGridView.count
> ```
> 
> instead of
> 
> ```
> ReorderableGridView
> ```


Sorry I didn't tell you my version first.
flutter: 3.4.0
reorderable_grid_view: ^2.2.5

And if I change to ReorderableGridView, how can I use the ReorderableSliverGridView's header and footer, I think those two function is great.

**Comment by huhuang03** [comment]
Maybe you can try `ReorderableSliverGridView's ` in version 2.2.6-alpha.1. Has `footer` and `header` option.

**Comment by mnba3223** [comment]
> 

Thanks for reply, I try to use ReorderableSliverGridView.count, But still has same problem.
 When I add  nested router, it will cause same height offset when drag the button.
 您好，感謝回覆，我後來使用 ReorderableSliverGridView.count 還是會在抓取時有y軸的偏移，原因是在當加入嵌套路由的用法後，會有一樣高度的偏移。

**Comment by huhuang03** [comment]
Can you provide a demo to show this.

I tested in `demo/main.dart Item("Sliver Grid", () => const DemoGridSliver())`. Which is corrent.

**Comment by mnba3223** [comment]
Hey, @huhuang03 , I modify your example(sorry not modify good), But bug is occur


sorry file is too big, 
https://drive.google.com/file/d/1ef-sf6gFnPDbzvb4_MuCkLozKSDc_PQr/view?usp=sharing

**Comment by huhuang03** [comment]
Hello. Please try version `2.2.6-alpha.2`. Should resolved.

**Comment by mnba3223** [comment]
> 

Thanks a lot, it's work!!!!!
