### ISSUE TITLE
Error while adding list of grid view widget('package:reorderable_grid_view/reorderable_grid_view.dart': Failed assertion: line 192 pos 12: 'toWrap.key != null': is not true.)

### ISSUE THREAD

**Issue by guruprasadhj** [huhuang03/reorderable_grid_view#5]
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building ReorderableGridView(dirty, dependencies: [_EffectiveTickerMode], state: _ReorderableGridViewState#af733(tickers: tracking 1 ticker)):
'package:reorderable_grid_view/reorderable_grid_view.dart': Failed assertion: line 192 pos 12: 'toWrap.key != null': is not true.

The relevant error-causing widget was: 
  ReorderableGridView file:///D:/workspace/ziya_launcher/lib/main.dart:54:21
When the exception was thrown, this was the stack: 
#2      _ReorderableGridViewState._wrap (package:reorderable_grid_view/reorderable_grid_view.dart:192:12)
#3      _ReorderableGridViewState.build (package:reorderable_grid_view/reorderable_grid_view.dart:341:20)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by huhuang03** [comment]
Looks like you should specify a key to the grid child.
``` dart
      return Card(
// specify a key.
        key: ValueKey(text),
        child: Text(text),
      );
````

**Comment by huhuang03** [comment]
I will close the issuse because it's seems solved. Please reopen it if still happen.
