### ISSUE TITLE
How to restrict dragging of widget inside a specific container or a prarent container & not allow dragging all over the phone screen ?

### ISSUE THREAD

**Issue by harishkthedeveloper** [huhuang03/reorderable_grid_view#52]
I want to restrict the dragging behaviour inside a container only but when we try to reorder here we can drag the widgets all over the screen.

Below is my widget tree

- Column[Container(child : xyzWidget), Container( child : ReorderableGridView) ]

My requirment is if user wants to reorder the widgets of ReorderableGridView he should be able to drag only within ReorderableGridView's parent container, he should not be able to drag all over the phone screen.

Please suggest your answers

Thanks  in advance

**Comment by huhuang03** [comment]
The reason is, this library use `Navigator`'s `Overlay`.

But I have no time to try to fix this recently. Sorry.

**Comment by huhuang03** [comment]
Please try version ~2.2.6-alpha.3~

Fixed `ReorderableGridView`. Not in `ReorderableSliverGridView`.

And you can see `demo/demo_custom` if you use `ReorderableWrapperWidget`

**Comment by huhuang03** [comment]
2.2.6-alpha.3 intro a new issue https://github.com/huhuang03/reorderable_grid_view/issues/54.

So don't use 2.2.6-alpha.3. And this issue is not resolved...

**Comment by huhuang03** [comment]
Fixed in `2.2.6-alpha.12`.  

Work in `ReorderableGridView`, not work in `ReorderableSliverGridView`, Please reopen a new issue if you want this in `ReorderableSliverGridView`
