### ISSUE TITLE
Children do not get order update on reorder

### ISSUE THREAD

**Issue by netapy** [huhuang03/reorderable_grid_view#54]
Hi thanks for this really cool library.

I've been trying to implement this on my app, but I've encountered errors : 
- The reorder occurs in the variable (when I print after user reorder, the list is updated without issue
- Refreshing the state of the app doesn't update the children's order.
- So basically when I put tile 3 before tile 1 --> the list becomes `[3,1,2]` but the displayed tiles are still `1,2,3`
- On Flutter (Channel stable, 3.3.9), with reorderable_grid_view: `^2.2.5` or `2.2.6-alpha.3`, on Android

This happens even on the pub.dev example your put out. 
Am I forgetting something ? Or is it a bug because of the recent flutter version ? 

Thanks !

**Comment by huhuang03** [comment]
Introed this issue in commit in https://github.com/huhuang03/reorderable_grid_view/pull/53

Please try version ~2.2.6-alpha.4~. Reverted.
