### ISSUE TITLE
Drugged item rebuild after reordered

### ISSUE THREAD

**Issue by aygunoz** [huhuang03/reorderable_grid_view#58]
Drugged item rebuild after reordered.

https://user-images.githubusercontent.com/74569642/211195540-ddbcb27f-8e7b-4c76-a42f-db383bf327c4.mov

**Comment by huhuang03** [comment]
Hello. you use `flutter_reorderable_grid_view: ^3.1.3.`?

It's not my project, so maybe you need create an issue to `flutter_reorderable_grid_view`

**Comment by aygunoz** [comment]
Hi, I am using reorderable_grid_view: ^2.2.6-alpha.6 and It's cover all my requireds and very efficient. Just I don't want rebuild the dragged item.

**Comment by aygunoz** [comment]
I just realized that It also rebuilding my other widget. Is there anyway to don't rebuild? Thank You

https://user-images.githubusercontent.com/74569642/211278103-7bf598b1-45de-4e91-8214-789246c532a5.mp4

**Comment by huhuang03** [comment]
Please try version
`2.2.6-alpha.7`.

**Comment by aygunoz** [comment]
It works for Reorderabblelist but it's rebuild still my widgetList.

https://user-images.githubusercontent.com/74569642/211341737-70eaece9-5246-44b0-8171-890c08a9173c.mp4

I wanted to show you how does it work with flutter_reorderable_grid_view: ^3.1.3 simple demo below video;

https://user-images.githubusercontent.com/74569642/211343362-64743d81-fa28-4ec1-8dd9-1e804438e7fa.mp4

**Comment by huhuang03** [comment]
If you passed an `dragWidgetBuilder` option to `ReorderableGridView`, Maybe you can try remove option `dragWidgetBuilder`.

**Comment by aygunoz** [comment]
I tried, it's not about that. Also I don't want to use dragWidgetBuilder but if I remove that, as you can see there is white background behind the widget so I used that and pass the widget to child.

https://user-images.githubusercontent.com/74569642/211463659-f9253409-4e0d-420a-a64f-8395dd214419.mp4

**Comment by huhuang03** [comment]
Sorry for my poor english, maybe I misunsderstood.

So you have a data list `ads`

And you have too widget, One is a list map by ads, and one is grid map by ads.

And then you reorder in grid. then list is reorderd, but list's item is rebuilded?

**Comment by huhuang03** [comment]
After some debug, I think reorder is not the real issue. Maybe the real issue is `you can't use the same ad widge both in list and grid`. But I'm not sure.

You can verify this by make some change to gridView's ad item(dont' reorder, get ride of reorder issue). Then scroll to the list, then scroll back to gridview, the gridview's item will rebuild.

**Comment by aygunoz** [comment]
If I understood correct. I tried as you said at video. I think it is not about gridView. Bc below answer, I showed you with other library, how does it work. I don't change anything just dependency changed.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/74569642/211562606-ed1756b7-51b4-4ea1-b6db-9d88a3948230.png">


https://user-images.githubusercontent.com/74569642/211561683-1d9caf4e-69f3-4c02-832b-4cbcf9a81f99.MP4

**Comment by huhuang03** [comment]
> 

Yes, it's not the real issue.

Pelease try version `^2.2.6-alpha.9`. 

If still not work, please read this:

The real issue maybe is relate to 
https://stackoverflow.com/questions/57704265/how-to-prevent-rebuild-statelesswidget-children-of-pageview#:~:text=You%20can%20achieve%20so%20by%20using

It's still can't work, you can post how your `ad widget` like.

I'm not very familiar to flutter, I used work with flutter, but fornow it's not.

**Comment by aygunoz** [comment]
Yes, I searched for this problem before :) I already did it. My code below;
I realize something that we use List<Widget>.generate at flutter_reorderable_grid_view: ^3.1.3 dependency. Could be bc of that ? I'll try they

```
import 'package:flutter/material.dart';

class VehicleAd extends StatefulWidget {
  final String id;
  const VehicleAd({Key? key, required this.id}) : super(key: key);

  @override
  State<VehicleAd> createState() => _VehicleAdState();
}

class _VehicleAdState extends State<VehicleAd>
    with AutomaticKeepAliveClientMixin<VehicleAd> {
  double selectedMenu = 0;
  @override
  Widget build(BuildContext context) {
    super.build(context);
    double height = MediaQuery.of(context).size.height;
    double width = MediaQuery.of(context).size.width;
    return SingleChildScrollView(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Text('Tersinesat\'tan temiz ilan'),
          Container(
            color: Colors.grey[300],
            height: 300,
            child: PageView(
              physics: BouncingScrollPhysics(),
              children: [
                Center(
                  child: Image.network(
                    width: width,
                    'https://picsum.photos/250?image=9',
                    fit: BoxFit.fitHeight,
                  ),
                ),
                Center(child: Text('2')),
                Center(child: Text('3')),
              ],
            ),
          ),
          const Text(
            'Aygün Özdemir',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
          ),
          Padding(
            padding: EdgeInsets.only(left: width / 32, right: width / 32),
            child: const Text(
              'Vasıta > Otomobil > BMW > 3 Serisi > 316ti > Compact > Otomatik',
              style: TextStyle(fontSize: 16),
              textAlign: TextAlign.center,
            ),
          ),
          Padding(
            padding: EdgeInsets.only(left: width / 18, right: width / 18),
            child: Wrap(
              children: [
                OutlinedButton(
                  onPressed: () {
                    setState(() {
                      selectedMenu = 0;
                      print(selectedMenu);
                    });
                  },
                  child: Text(
                    'İlan Bilgileri',
                    style: TextStyle(color: Colors.green[400]),
                  ),
                  style: OutlinedButton.styleFrom(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(6),
                        topRight: Radius.circular(0),
                        bottomLeft: Radius.circular(3),
                        bottomRight: Radius.circular(0),
                      ),
                    ),
                    foregroundColor: Colors.green,
                    side: selectedMenu == 0
                        ? BorderSide(width: 2, color: Colors.green)
                        : null,
                    fixedSize: Size(width / 18 * 5, 13.2),
                  ),
                ),
                OutlinedButton(
                  child: Text(
                    'Açıklama',
                    style: TextStyle(color: Colors.green[400]),
                  ),
                  style: OutlinedButton.styleFrom(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(0),
                    ),
                    foregroundColor: Colors.green,
                    side: selectedMenu == 1
                        ? BorderSide(width: 2, color: Colors.green)
                        : null,
                    fixedSize: Size(width / 18 * 5, 13.2),
                  ),
                  onPressed: () {
                    setState(() {
                      selectedMenu = 1;
                      print(selectedMenu);
                    });
                  },
                ),
                OutlinedButton(
                  child: Text(
                    'dede',
                    style: TextStyle(color: Colors.green[400]),
                  ),
                  style: OutlinedButton.styleFrom(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(0),
                        topRight: Radius.circular(6),
                        bottomLeft: Radius.circular(0),
                        bottomRight: Radius.circular(3),
                      ),
                    ),
                    foregroundColor: Colors.green,
                    side: selectedMenu == 2
                        ? BorderSide(width: 2, color: Colors.green)
                        : null,
                    fixedSize: Size(width / 18 * 5, 13.2),
                  ),
                  onPressed: () {
                    selectedMenu = 2;
                    setState(() {});
                  },
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  @override
  // TODO: implement wantKeepAlive
  bool get wantKeepAlive => true;
}

```

**Comment by aygunoz** [comment]
List.generate is not working too, whatever thank you for everything and you effort.

**Comment by huhuang03** [comment]
Ok, thank you for your patient.

But maybe the `bool get wantKeepAlive => true`; in Ad widget is not enough. Because it's not the direct child of `PageView`

You should wrapper `PageView`'s children with `KeepAlivePage`

**Comment by aygunoz** [comment]
Yeah, I found the problem. It was not about KeepAlivePage. Thank you for everything.
I changed this code;
 ```
FractionallySizedBox(
              heightFactor: 1 / _pageControllerX.viewportFraction,
              child: PageView(
                controller: _pageControllerY,
                physics: CustomTabBarViewScrollPhysics(),
                children: ads
                    .map((ad) => FractionallySizedBox(
                        widthFactor: 1 / _pageControllerY.viewportFraction,
                        child: ad))
                    .toList(),
              ),
            )
```
with 
```
FractionallySizedBox(
              heightFactor: 1 / _pageControllerX.viewportFraction,
              child: PageView(
                controller: _pageControllerY,
                physics: CustomTabBarViewScrollPhysics(),
                children: ads.map((ad) => ad).toList(),
              ),
            )
```

**Comment by aygunoz** [comment]
Also I want to ask, how can I remove white background of draggable item. You can see at below video.
And I think when we started to dragging the item, item was reflected as same widget state but right now its not in this version: reorderable_grid_view: ^2.2.6-alpha.9. Note: I don't edit dragWidgetBuilder.

https://user-images.githubusercontent.com/74569642/211622622-3846a452-ea83-4ed7-a800-48b01415494e.mp4

**Comment by huhuang03** [comment]
You can put `dragWidgetBuilder` back to remove to the white background. Something like this:
```
dragWidgetBuilder: (index, child) => child
```

If you not specify, the default dragWidgetBuilder show a white background.

**Comment by aygunoz** [comment]
I understood but If I put _dragWidgetBuilder_, it's effect item while dragging basically When I started to drag, item state changing with first inizilate state and when I stopped, it's return last state that when I started. Can we fix this :)? It would be great :)

**Comment by huhuang03** [comment]
You can try version `2.2.6-alpha.11`, and use the new dragWidgeteBuilder:

```
      dragWidgetBuilderV2: DragWidgetBuilderV2(
        isScreenshotDragWidget: true,
        builder: (index, child, screenshot) {
          if (screenshot == null) {
            return child;
          }
          return Image(image: screenshot);
        }
      ),
```

**Comment by aygunoz** [comment]
Many thanks. The library works perfectly right now.

**Comment by aygunoz** [comment]
Btw when I tried on android, there is a performance issue about take screenShoot. Do you think is there any other way to make this without take a screenShoot?

**Comment by huhuang03** [comment]
I can't think of any other way. Because the draged widget has it's  own state, which can't used in the dragWidgetBuilder.

**Comment by aygunoz** [comment]
It's okay, I am on the way to learn flutter and dart more. If I can figure out someway, I'll tell you 👍🏼

**Comment by huhuang03** [comment]
Ok!
