### ISSUE TITLE
Remove trailling + button

### ISSUE THREAD

**Issue by nicolasvahidzein** [huhuang03/reorderable_grid_view#65]
Thank you for this wonderful package.

I was wondering what the purpose of the trailing + button was and how we could remove it?

Thanks.

**Comment by huhuang03** [comment]
It's just for demonstrate the usage of `footer` option. And you can remove it  by delete this `footer` option.

[https://github.com/huhuang03/reorderable_grid_view/blob/a23f6c2320d74262f4611cda0955fbb84d5a454c/example/lib/demo/demo_reorderable_count.dart#L61]

**Comment by nicolasvahidzein** [comment]
thank you so much.
