### ISSUE TITLE
Add container decoration on startdrag

### ISSUE THREAD

**Issue by nicolasvahidzein** [huhuang03/reorderable_grid_view#66]
Is it possible to add a decoration when we start a drag of a particular item?

**Comment by huhuang03** [comment]
If you mean decoration the dragging widget, maybe you can try this option:

`dragWidgetBuilderV2`

https://github.com/huhuang03/reorderable_grid_view/blob/7bdc9c30df3180a0dfe0daa85bae0b9f57ef7091/example/lib/demo/demo_item_rebuild.dart#L79-L86

And the explain:

https://github.com/huhuang03/reorderable_grid_view#dragwidgetbuilderv2

**Comment by nicolasvahidzein** [comment]
This package is Gold!!! Thank you so much.
