### ISSUE TITLE
How do I remove the shadow?

### ISSUE THREAD

**Issue by eugenz3rr** [huhuang03/reorderable_grid_view#67]
Hi !

### Problem
I'm using your implementation in my app and realy like your work! Is there a way to solve this? When I drag & drop my custom widgets.
There is always an widget below mine that looks like a square and has it's own shadow. 

Is there a way to hide this shadow and or make the widget transparent?

![drag drop](https://github.com/huhuang03/reorderable_grid_view/assets/40625436/0907e739-b4f0-411f-9a6a-65aa221da389)

**Comment by huhuang03** [comment]
Hell, you can custom the draw widget like this:

![image](https://github.com/huhuang03/reorderable_grid_view/assets/4716706/60f3a093-76b4-4053-b85e-a46d3e39991a)

```
      dragWidgetBuilderV2: DragWidgetBuilderV2(builder: (int index, Widget child, ImageProvider? screenshot) {
        return child;
      }),
```

**Comment by eugenz3rr** [comment]
Thanks a lot! Sometimes I'm just blind ...
