### ISSUE TITLE
Allow for scrolling 

### ISSUE THREAD

**Issue by thunderbug1** [huhuang03/reorderable_grid_view#76]
The current behaviour is that the widet blocks every scrolling behaviour.
It would be useful for some applications if scrolling is still possible and a drag operation is only started after long pressing an item.

**Comment by huhuang03** [comment]
Hello, you can run the in-project examples, and see if Sliver Grid fit your need.

**Comment by thunderbug1** [comment]
Oh thank you for the hint, 
I am able to get it working by explicitly setting the scroll pyhsics with and without the Sliver Grid
```physics: const BouncingScrollPhysics()```

however, this has the sideffect that the cards in the grid can no longer be clicked. 
Clicking is only possible now if I start a drag event and then quickly click the card which is not quite the wanted behaviour.

**Comment by thunderbug1** [comment]
Thank you for the hint, I was able to get the wanted behavior by setting the scroll physics explicitly :)
```physics: const BouncingScrollPhysics()```
