### ISSUE TITLE
Setting childAspectRatio to lower than 1 is causing weird reorder animation

### ISSUE THREAD

**Issue by brightseagit** [huhuang03/reorderable_grid_view#8]
Hello, when I try to set childAspectRatio to lower than 1 then the reorder animation is not aligned and the reordered widgets are overlapping.
Also, the childAspectRatio property is very important for me because without it we will get overflow issues when trying to create bigger widgets in gridview.

Here is the sample video showcasing the issue:
![Android Emulator - New_Device_API_30_5554 2021-07-26 01-23-05](https://user-images.githubusercontent.com/72334435/126911803-73bb5ebd-00ed-493a-8d7a-054aa04f5879.gif)

**Comment by huhuang03** [comment]
Yes, it's a bug. You can try 1.1.0-alpha.1, fixed it.

**Comment by brightseagit** [comment]
Thank you for fixing it.
