### ISSUE TITLE
[Issue] Permanent overlay of the dragable on App

### ISSUE THREAD

**Issue by brightseagit** [huhuang03/reorderable_grid_view#9]
Hello, 
I am experiencing a bug where, if I press two draggables simultaneously, it causes a permanent overlay of the draggable on the application. And this only happens in the release apk.
I'm attaching a video showcasing the issue:

https://user-images.githubusercontent.com/72334435/126937541-4e0016cc-6eae-4aeb-8c6c-8937a0b18378.mp4

Thank you.

**Comment by huhuang03** [comment]
Looks like fixed in `1.1.0-alpha.2`.

**Comment by brightseagit** [comment]
Yes, I checked.
Thank you 👍 for fixing the issue.
